server:
  port : 8082

flowable:
  id-generator:
    datasource: flowable
  application:
    deployment-mode: classpath
  process:
    definition-location-prefix: classpath:/processes/

logging:
  level:
    org:
      flowable: DEBUG

spring:
  application:
    name: serviceB
#  datasource:
#    url: jdbc:postgresql://taconditioner.flycast:5432/postgres
#    username: postgres
#    password: AiGg4lSecXTv0Gg
#    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: AiGg4lSecXTv0Gg
    flowable:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=flowable
      username: postgres
      password: AiGg4lSecXTv0Gg
#      url: jdbc:postgresql://taconditioner.flycast:5432/postgres?currentSchema=flowable
#      username: postgres
#      password: AiGg4lSecXTv0Gg
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: modolncanombeh@gmail.com
    password: xoeflazcaqfmwoiz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

test:
  parent:
    is-new-parent: true


