server:
  port : 8081

flowable:
  id-generator:
    datasource: datasource
  application:
    deployment-mode: classpath

spring:
  application:
    name: serviceB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: modolncanombeh@gmail.com
    password: xoeflazcaqfmwoiz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer-group-1:
      group-id: transaction
      auto-offset-reset: latest

test:
  parent:
    is-new-parent: true


